# deployment

apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: []
  labels: {
    key: va,
    key2: val
  }
  name: xxx
  namespace: xxx
spec:
  replicas: 1
  selector:
    matchLabels: {

    }
  template:
    metadata:
      name: asd
      labels: {}
    spec:
      restartPolicy: always
      containers:
        - name: xxx
          image: xxx
          volumeMounts:
            - mountPath: ""
              name: ""
        - name: fluentd-sidecar
          image: xxx
          volumeMounts:
            - mountPath: ""
              name: ""

---
apiVersion: v1
kind: Service
metadata:
  name: xxx
spec:
  type: NodePort
  ports:
    - name: export
      nodePort: 8000
      port: 8800