# sudo docker run -d --restart=unless-stopped -p 80:80 -p 443:443 rancher/rancher:latest

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rancher
  namespace: kube-system
spec:
  selector:
    matchLabels:
      rancherPod: true
  serviceName: rancher-service
  replicas: 1
  template:
    metadata:
      name: rancher-pod
      namespace: kube-system
      labels:
        rancherPod: true
    spec:
      nodeName: xxx # 调度到特定node之上, 强制扩容可以考虑使用
      containers:
        - image: rancher/rancher:lastest
          name: rancherContainer
          ports:
            - containerPort: 80
              hostPort: 9999
            - containerPort: 443
          imagePullPolicy: Always
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: rancher-service
  namespace: kube-system
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 8080
    - port: 443
      nodePort: 8083
      targetPort: 3333
  selector:
    rancherPod: true